[env]
    _.file = "secrets.env.toml"

    DATA_DIR = "~/code/clippy/data"

    DB_URL = "sqlite:///reflex.db"
    PROJECT_DIR = "{{ config_root }}"
    WEB_APP_DIR = "wac_lab_app"
    # database_url = "sqlite:///.db/db.sqlite3" # db_url="sqlite:///reflex.db",

    # python specific
    _.python.venv.path = "/Users/graham/code/web-agent-collection-offline-dataset/.venv"
    _.python.venv.create = true


[tasks.app]
    description = 'run the app'
    run = "reflex run"
    alias = 'a'
    dir = "src/$WEB_APP_DIR"

[tasks."db:clean"]
    description = 'Clean the database'
    run = [
        "cd $PROJECT_DIR/src/$WEB_APP_DIR && trash reflex.db alembic.ini alembic/",
    ]

[tasks."db:init"]
    description = 'Setup the database'
    run = ["cd $PROJECT_DIR/src/$WEB_APP_DIR && reflex db init"]

[tasks."db:reset"]
    description = 'Reset the database'
    depends = ["db:clean", "db:init"]
    run = ["cd $PROJECT_DIR/src/$WEB_APP_DIR && reflex db reset"]

[tasks."db:migrate"]
    # -- then run like: `reflex db makemigrations --message $1`
    description = 'Migrate the database'
    run = [
        "echo doing migrate with message $1 ",
        "cd $PROJECT_DIR/src/$WEB_APP_DIR && reflex db migrate",
    ]
