[env]
    _.file = "../secrets.env.toml"

    DATA_DIR = "~/code/clippy/data"

    DB_URL = "sqlite:///reflex.db"
    # database_url = "sqlite:///.db/db.sqlite3" # db_url="sqlite:///reflex.db",

    # python specific
    _.python.venv.path = "/Users/graham/code/web-agent-collection-offline-dataset/.venv"
    _.python.venv.create = true


[tasks.app]
    description = 'Build the CLI'
    run = "reflex run"
    alias = 'a'                   # `mise run b`
    dir = "src/wac_lab"           # "{{cwd}}"               # run in user's cwd, default is the project's base directory
